-- 1. Create Database and Schema
CREATE DATABASE IF NOT EXISTS HOSPITALITY_DB;
USE DATABASE HOSPITALITY_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

-- 2. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 3. Create File Format for CSV.GZ
CREATE OR REPLACE FILE FORMAT RAW.GZIP_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = 'GZIP'
    NULL_IF = ('', 'NULL', 'null');

-- 4. Create External Stage pointing to AWS S3
CREATE OR REPLACE STAGE RAW.S3_RAW_STAGE
    URL = 's3://hospitality-de-pipeline-raw-fred/raw/'
    FILE_FORMAT = RAW.GZIP_CSV_FORMAT;